version: 2.0

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: mbti-career
  DOCKER_IMAGE_VERSION: latest

build-job:
  stage: build
  image: node:18-alpine
  commands:
    - npm install
    - npm run build
    - echo "Build completed"
  artifacts:
    paths:
      - .next/
      - node_modules/

deploy-job:
  stage: deploy
  image: alpine:latest
  commands:
    - echo "Deploying application..."
    - echo "Deploy completed"
  only:
    - main
  needs:
    - build-job 